openapi: 3.0.0
info:
  title: Simple Service
  description: API documentation for Simple Service project
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /v1/tasks:
    post:
      summary: Create a new task
      description: Creates a new task in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  example: "Implement new feature"
                description:
                  type: string
                  example: "Develop a new API endpoint for user management"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      task_id:
                        type: integer
                        example: 1
        '400':
          description: Invalid request format
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: "Invalid request body"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: "Failed to insert task"
